name: workflow-01
on: push

jobs:
    job01:
        runs-on: ubuntu-latest
        steps:

            - name: checkout
              uses: actions/checkout@v4
            - name: welcome message
              run: |
                  echo "this is my first worlkflow"
                  ls
                  cat Dockerfile
                  


            # - name: list the file
            #   run: ls

            # - name: read file
            #   run: cat Dockerfile
 

 